2024-12-19 16:50:19,626 | WARNING | Неверный тип данных для объекта Runner | test_run | 27
Traceback (most recent call last):
  File "C:\ProjectsForUniversity\pythonProject\My\m_12\tests_12_4.py", line 21, in test_run
    runer = rt.Runner(1997)
            ^^^^^^^^^^^^^^^
  File "C:\ProjectsForUniversity\pythonProject\My\m_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-19 16:50:19,627 | WARNING | Неверная скорость для Runner | test_walk | 16
Traceback (most recent call last):
  File "C:\ProjectsForUniversity\pythonProject\My\m_12\tests_12_4.py", line 10, in test_walk
    walker = rt.Runner('Евгений', -3)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProjectsForUniversity\pythonProject\My\m_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -3
